### ISSUE TITLE
Features I'd like to see in this AntiCheat

### ISSUE THREAD

**Issue by ClydeplayzYT590** [VeroxCode/Guardian-AntiCheat#1]
Hey! I just saw this plugin and there are some things I'd like to see implemented to this anticheat plugin:

- Customizable Prefix
- Customizable Alert/Fail/Flag message
- Be able to turn on and off anticheat notifications for only yourself
- CPS Detection
- Alerts Delay (Too many notifications being sent in the chat like every millisecond is annoying)

**Comment by VeroxCode** [comment]
Is now all in the latest release version & on the master branch
