### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by gamegam** [VeroxCode/Guardian-AntiCheat#9]
[Guardian] You have been Kicked for Cheating!

Using the source below, it will be banished.

If you are within 12m of an entity, teleport to Y+10 above the entity to move and lock the screen and hit. When that entity dies, go straight to the other entity and kill it in the exact same pattern. This pattern lasts for 15 seconds. When this skill ends, it will teleport to the verge of activation, leaving only 1 HP of health. It's a skill.

**Comment by VeroxCode** [comment]
what?

**Comment by gamegam** [comment]
> what?

I do not know. The only thing you can do is teleport and catch mobs at 12m.
